# Generated by Django 3.2.8 on 2021-10-13 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211011_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='videoAmount',
        ),
    ]
