# Generated by Django 3.2.8 on 2022-03-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subCategory',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
